server:
  port: 8080

spring:
  application:
    name: SGRSH - Sistema de Gestión de Reservas y Servicios Hoteleros

  datasource:
    url: jdbc:mysql://localhost:3306/hotel_tolimagrande?useSSL=false&serverTimezone=UTC
    username: root
    password: Lexus97@
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
  main:
    allow-circular-references: true

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 20
          order_inserts: true
          order_updates: true

  json:
    jackson:
      serialization:
        write-dates-as-timestamps: false

# Configuración de SpringDoc OpenAPI (Swagger) reactivada
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
  show-actuator: false

# Datos generales y JWT indispensables para tus clases de configuración
app:
  name: SGRSH
  version: 1.0.0
  description: Sistema para la Gestión de Reservas y Servicios Hoteleros
  jwt:
    secret: your-secret-key-here-min-256-chars-your-secret-key-here-min-256-chars
    expiration: 86400000
